create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  stripe_session_id text not null unique,
  email text not null,
  status text not null check (status in ('paid', 'processing', 'failed', 'refunded')),
  currency text not null default 'cad',
  total_amount integer not null check (total_amount >= 0),
  shipping jsonb not null default '{}'::jsonb,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);

alter table public.orders enable row level security;

revoke all on public.orders from anon, authenticated;
